BTW { "output": "WIN\n" }
HAI 1.3
I HAS A DAB ITZ 10
HOW IZ I TEST
    I HAS A FOO ITZ 10
    I HAS A GLOBAL ITZ SUM OF 10 AN 123
    GLOBAL IS NOW A YARN
    FOUND YR GLOBAL
IF U SAY SO

VISIBLE BOTH SAEM I IZ TEST MKAY AN "133"
KTHXBYE
