BTW {"output": "\n0\n0\nFAIL\nNOOB"}
HAI 1.2
I HAS A TEST ITZ A YARN
VISIBLE TEST

I HAS A TEST2 ITZ A NUMBR
VISIBLE TEST2

I HAS A TEST3 ITZ A NUMBAR
VISIBLE TEST3

I HAS A TEST4 ITZ A TROOF
VISIBLE TEST4

I HAS A TEST5 ITZ A NOOB
VISIBLE TEST5
KTHXBYE
