BTW { "output": "RED FISH\nDONE\nYELLOW FISH\nFISH HAS A FLAVOR\nDONE\nFISH HAS A FLAVOR\nDONE\nFISH HAS A FLAVOR\nDONE\nFISH IS TRANSPARENT\nDONE\n" }
HAI 1.2
HOW IZ I FISH YR COLOR
    COLOR, WTF?
      OMG "R"
        VISIBLE "RED FISH"
        GTFO
      OMG "Y"
        VISIBLE "YELLOW FISH"
      OMG "G"
      OMG "B"
        VISIBLE "FISH HAS A FLAVOR"
        GTFO
      OMGWTF
        VISIBLE "FISH IS TRANSPARENT"
    OIC
    VISIBLE "DONE"
IF U SAY SO

I IZ FISH YR "R" MKAY
I IZ FISH YR "Y" MKAY
I IZ FISH YR "G" MKAY
I IZ FISH YR "B" MKAY
I IZ FISH YR "T" MKAY
KTHXBYE
