BTW { "output": "WAS FOO\nWAS BAR?\nFALLTHROUGH\nWAS BAR?\nFALLTHROUGH\n" }
HAI 1.3
HOW IZ I SWITCH YR VALUE
    VALUE, WTF?
        OMG "FOO"
            VISIBLE "WAS FOO"
        OMG "BAR"
            VISIBLE "WAS BAR?"
        OMGWTF
            VISIBLE "FALLTHROUGH"
    OIC
IF U SAY SO

I IZ SWITCH YR "FOO" MKAY
I IZ SWITCH YR "BAR" MKAY
KTHXBYE
