[package]
name = "lulz"
version = "0.1.0"
authors = ["Jonathan Li <30177086+MonliH@users.noreply.github.com>"]
edition = "2018"

[dependencies]
codespan-reporting = "0.11.1"
clap = "3.0.0-beta.2"
colored = "2"
smallvec = "1"
smol_str = "0.1"
rustc-hash = "1.1.0"
unicode_names2 = "0.4.0"
derivative = "2.2.0"

[profile.release]
lto = true
