[package]
name = "lulz"
version = "0.1.0"
authors = ["Jonathan Li <30177086+MonliH@users.noreply.github.com>"]
edition = "2018"

[dependencies]
codespan-reporting = "0.11.1"
smallvec = "1"
smol_str = "0.1"
rustc-hash = "1.1.0"
unicode_names2 = "0.4.0"
pico-args = { version = "0.4.1", features = ["short-space-opt"] }
toolshed = "0.8.1"
lightning-sys = { git = "https://github.com/Petelliott/lightning-sys", branch = "master" }

[profile.release]
lto = true
