BTW { "output": "10\n10\n" }
HAI 1.3
I HAS A X ITZ 10
BTW HOW IZ I PRINT_X
BTW VISIBLE X
BTW F U SAY SO

BTW OW IZ I OUTER

BTW IZ PRINT_X MKAY
BTW FOUND YR PRINT_X
BTW F U SAY SO

BTW HAS A FN ITZ I IZ OUTER MKAY
BTW I IZ FN MKAY
KTHXBYE
