BTW { "status": "error" }
HAI 1.3
HOW IZ I OUTER
    I HAS A X ITZ 10
    HOW IZ I TEST YR VALUE
        FOUND YR X
    IF U SAY SO

    HOW IZ I TEST YR VALUE
        FOUND YR X
    IF U SAY SO
IF U SAY SO
KTHXBYE
