BTW { "output": "value 123\n" }
HAI 1.3
HOW IZ I OUTER
    I HAS A X ITZ "value"

    HOW IZ I TEST YR VALUE
        FOUND YR ":{X} :{VALUE}"
    IF U SAY SO
    
    VISIBLE I IZ TEST YR 123 MKAY
IF U SAY SO

I IZ OUTER MKAY
KTHXBYE
