BTW { "output": "1\n3\n4\n6\n" }
HAI 1.3
HOW IZ I OUTER
    I HAS A X ITZ 0

    HOW IZ I TEST
        X R SUM OF X AN 1
        VISIBLE X
    IF U SAY SO

    HOW IZ I TEST2
        X R SUM OF X AN 2
        VISIBLE X
    IF U SAY SO

    I IZ TEST MKAY
    I IZ TEST2 MKAY
    I IZ TEST MKAY
    I IZ TEST2 MKAY
IF U SAY SO

I IZ OUTER MKAY
KTHXBYE
