BTW { "output": "10\n" }
HAI 1.3
I HAS A X ITZ 10
HOW IZ I OUTER YR FLAG
    FLAG, O RLY?
        YA RLY
            FOUND YR X
        NO WAI
            FOUND YR I IZ OUTER YR WIN MKAY
    OIC
IF U SAY SO

HOW IZ I TEST
    VISIBLE I IZ OUTER YR FAIL MKAY
IF U SAY SO

I IZ TEST MKAY
KTHXBYE
