BTW { "output": "value\n" }
HAI 1.3
HOW IZ I OUTER
    I HAS A X ITZ "value"

    HOW IZ I TEST
        FOUND YR X
    IF U SAY SO

    FOUND YR TEST
IF U SAY SO

I HAS A INNER ITZ I IZ OUTER MKAY
VISIBLE I IZ INNER MKAY
KTHXBYE
