BTW { "output": "WIN\nWIN\nFAIL\nFAIL\nWIN\nFAIL\n" }
HAI 1.3
HOW IZ I TEST1
IF U SAY SO

HOW IZ I TEST2
IF U SAY SO

VISIBLE BOTH SAEM TEST1 AN TEST1
VISIBLE BOTH SAEM TEST2 AN TEST2
VISIBLE BOTH SAEM TEST1 AN TEST2
VISIBLE BOTH SAEM TEST2 AN TEST1

I HAS A TEST3 ITZ TEST1
VISIBLE BOTH SAEM TEST1 AN TEST3
VISIBLE BOTH SAEM TEST2 AN TEST3
KTHXBYE
