BTW { "output": "WIN\nWIN\nWIN\nFAIL\n" }
HAI 1.3
I HAS A TEST ITZ 123
VISIBLE BOTH SAEM TEST 123
VISIBLE BOTH SAEM TEST AN 123.0
VISIBLE BOTH SAEM 123.0 AN TEST
VISIBLE BOTH SAEM TEST AN 123.1
KTHXBYE
