BTW { "output": "WIN\nWIN\nWIN\nFAIL\nFAIL\nFAIL\nFAIL\nFAIL\n" }
HAI 1.3
VISIBLE ALL OF WIN AN WIN AN WIN MKAY
VISIBLE ALL OF WIN WIN WIN MKAY
VISIBLE ALL OF WIN MKAY
VISIBLE ALL OF FAIL MKAY
VISIBLE ALL OF FAIL FAIL FAIL MKAY
VISIBLE ALL OF WIN FAIL FAIL FAIL MKAY
VISIBLE ALL OF WIN WIN WIN FAIL MKAY

VISIBLE ALL OF WIN WIN WIN 0 MKAY
KTHXBYE
