BTW { "output": "WIN\nFAIL\nFAIL\nFAIL\nWIN\n" }
HAI 1.3
VISIBLE BOTH OF WIN AN WIN
VISIBLE BOTH OF FAIL AN WIN
VISIBLE BOTH OF WIN AN FAIL
VISIBLE BOTH OF FAIL AN FAIL
VISIBLE BOTH OF 1 AN 1
KTHXBYE
