BTW { "output": "WIN\nWIN\nWIN\nFAIL\nFAIL\nWIN\nWIN\nWIN\n" }
HAI 1.3
VISIBLE ANY OF WIN AN WIN AN WIN MKAY
VISIBLE ANY OF WIN WIN WIN MKAY
VISIBLE ANY OF WIN MKAY
VISIBLE ANY OF FAIL MKAY
VISIBLE ANY OF FAIL FAIL FAIL MKAY
VISIBLE ANY OF WIN FAIL FAIL FAIL MKAY
VISIBLE ANY OF WIN WIN WIN FAIL MKAY

VISIBLE ANY OF WIN WIN WIN 0 MKAY
KTHXBYE
