BTW { "output": "WIN\nWIN\nWIN\nFAIL\nWIN\n" }
HAI 1.3
VISIBLE EITHER OF WIN AN WIN
VISIBLE EITHER OF FAIL AN WIN
VISIBLE EITHER OF WIN AN FAIL
VISIBLE EITHER OF FAIL AN FAIL
VISIBLE EITHER OF 0 AN 1
KTHXBYE
