BTW { "output": "WIN\nFAIL\nFAIL\nWIN\nWIN\nFAIL\nWIN\nWIN\nFAIL\nWIN\n" }
HAI 1.3
VISIBLE MAEK "hello123" A TROOF
VISIBLE MAEK "" A TROOF
VISIBLE MAEK 0 A TROOF
VISIBLE MAEK 1 A TROOF
VISIBLE MAEK 123 A TROOF
VISIBLE MAEK 0.0 A TROOF
VISIBLE MAEK 0.0001 A TROOF

VISIBLE MAEK WIN A TROOF
VISIBLE MAEK FAIL A TROOF

HOW IZ I TEST
IF U SAY SO

VISIBLE MAEK TEST A TROOF
KTHXBYE
