BTW { "output": "hi\nWIN\nFAIL\n10\nBYE\nNOOB\n" }
HAI 1.3
I HAS A ARRAY ITZ A LIZT
PUT "hi" INTO ARRAY    BTW 0
PUT "BYE" INTO ARRAY   BTW 1
PUT 10 INTO ARRAY      BTW 2
PUT WIN INTO ARRAY     BTW 3
PUT FAIL INTO ARRAY    BTW 4
PUT NOOB INTO ARRAY    BTW 5

VISIBLE GRAB 0 FRUM ARRAY
VISIBLE GRAB 3 FRUM ARRAY
VISIBLE GRAB 4 FRUM ARRAY
VISIBLE GRAB 2 FRUM ARRAY
VISIBLE GRAB 1 FRUM ARRAY
VISIBLE GRAB 5 FRUM ARRAY
KTHXBYE

