BTW {"output": "[x, BYE, 10, WIN, FAIL, y]"}
HAI 1.3
I HAS A ARRAY ITZ A LIZT
PUT "hi" INTO ARRAY
PUT "BYE" INTO ARRAY
PUT 10 INTO ARRAY
PUT WIN INTO ARRAY
PUT FAIL INTO ARRAY
PUT NOOB INTO ARRAY

SHUV "x" INTO FRUNT OF ARRAY
SHUV "y" INTO BAK OF ARRAY

VISIBLE ARRAY
KTHXBYE
