BTW {"output": "3\n103\n"}
HAI 1.3
I HAS A ARRAY ITZ A LIZT
PUT "hi" INTO ARRAY
PUT "BYE" INTO ARRAY
PUT 10 INTO ARRAY

VISIBLE LANGTH OF ARRAY

IM IN YR LOOP UPPIN YR i TIL BOTH SAEM i AN 100
    PUT "hello" INTO ARRAY
IM OUTTA YR LOOP

VISIBLE LANGTH OF ARRAY
KTHXBYE
