BTW {"output": "[hi, BYE, 10, WIN, FAIL, NOOB]\n"}
HAI 1.3
I HAS A ARRAY ITZ A LIZT
BTW Pass by reference
I HAS A COPY ITZ ARRAY

PUT "hi" INTO ARRAY
PUT "BYE" INTO ARRAY
PUT 10 INTO ARRAY
PUT WIN INTO ARRAY
PUT FAIL INTO ARRAY
PUT NOOB INTO ARRAY

VISIBLE COPY
KTHXBYE
