BTW {"output": "[hi, BYE, 10, HI, FAIL, HAI]"}
HAI 1.3
I HAS A ARRAY ITZ A LIZT
PUT "hi" INTO ARRAY
PUT "BYE" INTO ARRAY
PUT 10 INTO ARRAY
PUT WIN INTO ARRAY
PUT FAIL INTO ARRAY
PUT NOOB INTO ARRAY

SHUV "HI" INTO 3 OF ARRAY
SHUV "HAI" INTO 5 OF ARRAY

VISIBLE ARRAY
KTHXBYE
