HAI 1.3
HOW IZ I FIB YR N
    I HAS A SML ITZ SMALLR OF N AN 1
    BOTH SAEM N AN SML
    O RLY?
        YA RLY
            FOUND YR 1
        NO WAI
            I HAS A FIRST ITZ I IZ FIB YR DIFF OF N AN 1 MKAY
            I HAS A SECOND ITZ I IZ FIB YR DIFF OF N AN 2 MKAY
            FOUND YR SUM OF FIRST AN SECOND
    OIC
IF U SAY SO

VISIBLE I IZ FIB YR 30 MKAY
KTHXBYE
