BTW { "output": "10946\n" }
HAI 1.3

BTW THIS IS THE SLOW FIB FUNCTION, WITH EXPONENTIAL RUNTIME
HOW IZ I FIB YR N
    BOTH SAEM N AN SMALLR OF N AN 1
    O RLY?
        YA RLY
            FOUND YR 1
        NO WAI
            I HAS A FIRST ITZ I IZ FIB YR DIFF OF N AN 1 MKAY
            I HAS A SECOND ITZ I IZ FIB YR DIFF OF N AN 2 MKAY
            FOUND YR SUM OF FIRST AN SECOND
    OIC
IF U SAY SO

VISIBLE I IZ FIB YR 20 MKAY
KTHXBYE
