BTW { "output": "123\n" }
HAI 1.2
HOW IZ I PRINT_THING YR THING
    VISIBLE THING
IF U SAY SO

I HAS A FN ITZ PRINT_THING

HOW IZ I CALL YR FUNC
    I IZ FUNC YR 123 MKAY
IF U SAY SO

I IZ CALL YR FN MKAY
KTHXBYE
