BTW { output: "3628800\n" }
HAI 1.3
HOW IZ I FACTORIAL YR N
    BOTH SAEM N AN 1, O RLY?
        YA RLY
            FOUND YR 1
        NO WAI
            I HAS A DEC ITZ DIFF OF N AN 1
            FOUND YR PRODUKT OF N AN I IZ FACTORIAL YR DEC MKAY
    OIC
IF U SAY SO

VISIBLE I IZ FACTORIAL YR 10 MKAY
KTHXBYE
