BTW { output: "3628800\n" }
HAI 1.3
HOW IZ I FACTORIAL YR N
    BOTH SAEM N AN 0, O RLY?
        YA RLY
            FOUND YR 1
        NO WAI
            FOUND YR PRODUKT OF I IZ FACTORIAL YR DIFF OF N AN 1 MKAY AN N
    OIC
IF U SAY SO

VISIBLE I IZ FACTORIAL YR 10 MKAY
KTHXBYE
