BTW { "output": "FAIL\nWIN\nFAIL\nWIN\nFAIL\nWIN\n" }
HAI 1.3
VISIBLE IZ 10 LES THEN 3
VISIBLE IZ 10 GRETER THEN 3

VISIBLE IZ 10 GRETER THEN 10
VISIBLE IZ 10 GRETER EQ THEN 10

VISIBLE IZ 10 LES THEN 10
VISIBLE IZ 10 LES EQ THEN 10
KTHXBYE
