BTW { "trials": 5, "reps": 20 }
HAI 1.3

BTW THIS IS THE SLOW FIB FUNCTION, WITH EXPONENTIAL RUNTIME
HOW IZ I FIB YR N
    BOTH SAEM N AN SMALLR OF N AN 2
    O RLY?
        YA RLY
            FOUND YR N
        NO WAI
            FOUND YR SUM OF I IZ FIB YR DIFF OF N AN 1 MKAY AN I IZ FIB YR DIFF OF N AN 2 MKAY
    OIC
IF U SAY SO

VISIBLE I IZ FIB YR 37 MKAY
KTHXBYE
