BTW { "trials": 5, "reps": 20 }
HAI 1.3

BTW THIS IS THE SLOW FIB FUNCTION, WITH EXPONENTIAL RUNTIME
HOW IZ I FIB YR N
    BOTH SAEM N AN SMALLR OF N AN 1.0
    O RLY?
        YA RLY
            FOUND YR 1.0
        NO WAI
            FOUND YR SUM OF I IZ FIB YR DIFF OF N AN 1.0 MKAY AN I IZ FIB YR DIFF OF N AN 2.0 MKAY
    OIC
IF U SAY SO

BTW VISIBLE I IZ FIB YR 46.0 MKAY
VISIBLE PRODUKT OF 123190231029410293.0 AN 9999999.0
KTHXBYE
