name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install compilers
      run: sudo apt-get install tcc gcc clang
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test
    - name: Run test suite (gcc)
      run: python3 run_tests.py gcc
    - name: Run test suite (clang)
      run: python3 run_tests.py clang
    - name: Run test suite (tcc)
      run: python3 run_tests.py tcc
